baseurl      = "http://localhost"
title        = "Samir Tapiero"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

[[params.social]]
  name = "email"
  url  = "samtapiero@gmail.com"

[[params.social]]
  name = "github"
  url  = "https://github.com/blacksam07"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/samirtapiero"

  # Subtitle for home
  homeSubtitle = "Software Engineer"

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

[taxonomies]
    category = "blog"
    tag      = "tags"

[languages]
  [languages.en]
    title = "Samir Tapiero"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params.logo]
      logoText = "Samir Tapiero"
      logoHomeLink = "/en"
  [languages.es]
    title = "Samir Tapiero"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.es.params.logo]
      logoText = "samir tapiero"
      logoHomeLink = "/es"

  # And you can even create generic menu
  [[menu.main]]

  [params.footer]
    trademark = true
    rss = false
    copyright = false
    author = true

    topText = ['Hello for everyone']
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Usign the theme <a href=\"https://themes.gohugo.io/themes/hugo-theme-hello-friend-ng\">hello-friend-ng</a>"
    ]